### PR TITLE
Public/7.9 freebsd

### PR DESCRIPTION
**Pull request by fsbruva**
Good day-

Here's a comprehensive FreeBSD branch. It fixes the build process for use with modern clang (tested with 4.0.0), c++ std, and the latest ICU (59.1). It works for me, I am curious if it works for you as well.

As an aside, I use the p5-IO-Socket-SSL port for my install, rather than include the Mozilla::CA, Net::SSLeay and IO::Socket::SSL as individual tarballs from CPAN.org. 

Sincerely,
Matt

### CODE REVIEW

**Comment by mnd999** [comment]
Thanks, this looks like a significant amount of work. I’ll try to take a look as soon as possible.

**Comment by mnd999** [comment]
@fsbruva What is the plan for this long term? Are you wanting to merge it upstream? Or incorporate it into the FreeBSD port?

**Comment by fsbruva** [comment]
@mnd999 Long term, I would love to merge it upstream. But full merging may be delayed because of the c++11 build & subsequent runtime dependency that ICU 59 brings. I have separate upstream PRs for ICU 58.2 (for all platforms), Perl 5.26 support and the FreeBSD audio tools. I was mostly hoping you could take a look and help me find any problems with this branch.

**Comment by fsbruva** [comment]
This branch also contains the regression reported here: https://github.com/Logitech/slimserver-vendor/issues/55

**Comment by mnd999** [comment]
Most of this has now been picked up by the FreeBSD port. We got some nice feedback:

This is just a quick note of thanks for maintaining the current LMS port. I have installed it in a jail on Nas4Free and it works perfectly. I’ve been running LMS for years (10 or more) and this is the easiest it’s been to install it on Freebsd. 

Thanks again, Stuart

**Comment by fsbruva** [comment]
Glad the work is appreciated. This PR has been overtaken by events.

**Pull request closed without merging**
